export const bookConstants = {
    DELETE_REQUEST: 'BOOK_DELETE_REQUEST',
    DELETE_SUCCESS: 'BOOK_DELETE_SUCCESS',
    DELETE_FAILURE: 'BOOK_DELETE_FAILURE',

    EDIT_REQUEST: 'BOOK_EDIT_REQUEST',
    EDIT_SUCCESS: 'BOOK_EDIT_SUCCESS',
    EDIT_FAILURE: 'BOOK_EDIT_SUCCESS',

    CREATE_REQUEST: 'BOOK_CREATE_REQUEST',
    CREATE_SUCCESS: 'BOOK_CREATE_SUCCESS',
    CREATE_FAILURE: 'BOOK_CREATE_FAILURE',

    GETALL_REQUEST: 'BOOK_GETALL_REQUEST',
    GETALL_SUCCESS: 'BOOK_GETALL_SUCCESS',
    GETALL_FAILURE: 'BOOK_GETALL_FAILURE',
    FIND_FETCH: 'FETCH_BOOKS_SUCCESS'
}